import type { Brand, Retailer, Salesperson } from '../types'
import { WALMART_AUTHORIZED_ITEMS } from './walmart-authorized'

export const BRAND_COLORS: Record<Brand, string> = {
  tuscanini: '#1B4D3E',
  kedem: '#991B1B',
  gefen: '#7C3AED',
  liebers: '#C41E3A',
  haddar: '#1E3A8A',
  osem: '#059669',
  other: '#64748B',
}

export const mockRetailers: Retailer[] = [
  {
    id: 'ret-1',
    kaycoAccountPatterns: ['WAL-MART'],
    name: 'Walmart',
    status: 'active',
    tier: 'enterprise',
    defaultTierCount: 4,
    maxDisplayHeight: 60,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 4700,
    regions: ['Northeast', 'Southeast', 'Midwest', 'West', 'Southwest'],
    headquartersCity: 'Bentonville',
    headquartersState: 'AR',
    accountManager: 'David Greenfield',
    contractStart: '2024-01-15',
    contractEnd: '2026-12-31',
    website: 'walmart.com',
    tags: ['top-account', 'holiday-priority', 'endcap-eligible'],
    contacts: [
      { id: 'c-1', name: 'Jennifer Walsh', title: 'Category Manager — Ethnic Foods', email: 'j.walsh@walmart.com', phone: '(479) 555-0142', isPrimary: true },
      { id: 'c-2', name: 'Marcus Rivera', title: 'Display Compliance Lead', email: 'm.rivera@walmart.com', phone: '(479) 555-0198', isPrimary: false },
      { id: 'c-3', name: 'Sarah Kim', title: 'Procurement Specialist', email: 's.kim@walmart.com', phone: '(479) 555-0167', isPrimary: false },
    ],
    authorizedItems: WALMART_AUTHORIZED_ITEMS,
    compliance: [
      { id: 'comp-1', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-02-15', nextAuditDate: '2026-08-15' },
      { id: 'comp-2', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-01-20', nextAuditDate: '2026-07-20' },
      { id: 'comp-3', requirement: 'Kosher Certification Documentation', status: 'compliant', lastAuditDate: '2026-03-01', nextAuditDate: '2026-09-01' },
      { id: 'comp-4', requirement: 'GTIN/UPC Barcode Verification', status: 'compliant', lastAuditDate: '2026-02-01', nextAuditDate: '2026-08-01' },
      { id: 'comp-5', requirement: 'Supplier Insurance & Liability', status: 'action-required', lastAuditDate: '2025-12-01', nextAuditDate: '2026-06-01', notes: 'Updated COI needed by June — current policy expiring' },
    ],
    performance: { totalRevenueMTD: 284500, totalRevenueYTD: 1842000, avgOrderValue: 12800, fillRate: 97.2, onTimeDelivery: 94.8, returnRate: 1.3, displayComplianceScore: 92 },
    displayHistory: [
      { id: 'dh-1', projectName: 'RH 2026 — Walmart', holiday: 'rosh-hashanah', createdAt: '2026-03-01', status: 'active', tierCount: 4, productCount: 7 },
      { id: 'dh-2', projectName: 'Pesach 2026 — Walmart', holiday: 'pesach', createdAt: '2026-01-15', status: 'draft', tierCount: 4, productCount: 3 },
      { id: 'dh-3', projectName: 'RH 2025 — Walmart', holiday: 'rosh-hashanah', createdAt: '2025-03-10', status: 'completed', tierCount: 4, productCount: 8 },
      { id: 'dh-4', projectName: 'Pesach 2025 — Walmart', holiday: 'pesach', createdAt: '2025-01-05', status: 'completed', tierCount: 3, productCount: 6 },
    ],
    notes: 'Largest account by volume. Holiday endcap program renewed through 2026. Requires 4-week lead time on new item authorizations.',
  },
  {
    id: 'ret-2',
    kaycoAccountPatterns: ['COSTCO'],
    name: 'Costco',
    status: 'active',
    tier: 'enterprise',
    defaultTierCount: 3,
    maxDisplayHeight: 72,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 591,
    regions: ['Northeast', 'West', 'Southeast'],
    headquartersCity: 'Issaquah',
    headquartersState: 'WA',
    accountManager: 'David Greenfield',
    contractStart: '2024-06-01',
    contractEnd: '2027-05-31',
    website: 'costco.com',
    tags: ['top-account', 'bulk-format', 'warehouse-club'],
    contacts: [
      { id: 'c-4', name: 'Brian Cho', title: 'Assistant Buyer — Specialty Foods', email: 'b.cho@costco.com', phone: '(425) 555-0231', isPrimary: true },
      { id: 'c-5', name: 'Amanda Torres', title: 'Vendor Relations Manager', email: 'a.torres@costco.com', phone: '(425) 555-0289', isPrimary: false },
    ],
    authorizedItems: [],
    compliance: [
      { id: 'comp-6', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-01-10', nextAuditDate: '2026-07-10' },
      { id: 'comp-7', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-02-05', nextAuditDate: '2026-08-05' },
      { id: 'comp-8', requirement: 'Kosher Certification Documentation', status: 'compliant', lastAuditDate: '2026-01-15', nextAuditDate: '2026-07-15' },
      { id: 'comp-9', requirement: 'Warehouse Club Packaging Standards', status: 'pending-review', lastAuditDate: '2025-11-20', nextAuditDate: '2026-05-20', notes: 'New multi-pack requirements under review for Q3' },
    ],
    performance: { totalRevenueMTD: 198700, totalRevenueYTD: 1156000, avgOrderValue: 24500, fillRate: 98.1, onTimeDelivery: 96.5, returnRate: 0.8, displayComplianceScore: 96 },
    displayHistory: [
      { id: 'dh-5', projectName: 'RH 2026 — Costco', holiday: 'rosh-hashanah', createdAt: '2026-02-20', status: 'draft', tierCount: 3, productCount: 5 },
      { id: 'dh-6', projectName: 'RH 2025 — Costco', holiday: 'rosh-hashanah', createdAt: '2025-02-15', status: 'completed', tierCount: 3, productCount: 6 },
    ],
    notes: 'Requires bulk/club-pack formats. 72" max display height allows taller builds. High velocity on Bamba and grape juice.',
  },
  {
    id: 'ret-3',
    kaycoAccountPatterns: ['SHOPRITE', 'WAKEFERN GENERAL'],
    name: 'ShopRite',
    status: 'active',
    tier: 'premium',
    defaultTierCount: 4,
    maxDisplayHeight: 60,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 320,
    regions: ['Northeast', 'Mid-Atlantic'],
    headquartersCity: 'Keasbey',
    headquartersState: 'NJ',
    accountManager: 'Rachel Hoffman',
    contractStart: '2024-04-01',
    contractEnd: '2026-03-31',
    website: 'shoprite.com',
    tags: ['kosher-strong', 'regional-key', 'cooperative'],
    contacts: [
      { id: 'c-6', name: 'Michael Stern', title: 'VP Ethnic & Specialty', email: 'm.stern@shoprite.com', phone: '(732) 555-0144', isPrimary: true },
      { id: 'c-7', name: 'Lisa Parikh', title: 'Category Analyst', email: 'l.parikh@shoprite.com', phone: '(732) 555-0177', isPrimary: false },
      { id: 'c-8', name: 'Dan Cooper', title: 'Store Operations Director', email: 'd.cooper@shoprite.com', phone: '(732) 555-0199', isPrimary: false },
    ],
    authorizedItems: [],
    compliance: [
      { id: 'comp-10', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-02-20', nextAuditDate: '2026-08-20' },
      { id: 'comp-11', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-01-15', nextAuditDate: '2026-07-15' },
      { id: 'comp-12', requirement: 'Kosher Certification Documentation', status: 'compliant', lastAuditDate: '2026-03-05', nextAuditDate: '2026-09-05' },
      { id: 'comp-13', requirement: 'Co-op Advertising Compliance', status: 'compliant', lastAuditDate: '2026-01-30', nextAuditDate: '2026-07-30' },
      { id: 'comp-14', requirement: 'GTIN/UPC Barcode Verification', status: 'compliant', lastAuditDate: '2026-02-10', nextAuditDate: '2026-08-10' },
    ],
    performance: { totalRevenueMTD: 156200, totalRevenueYTD: 987000, avgOrderValue: 8900, fillRate: 95.4, onTimeDelivery: 93.1, returnRate: 1.8, displayComplianceScore: 88 },
    displayHistory: [
      { id: 'dh-7', projectName: 'RH 2026 — ShopRite', holiday: 'rosh-hashanah', createdAt: '2026-02-28', status: 'active', tierCount: 4, productCount: 9 },
      { id: 'dh-8', projectName: 'Pesach 2026 — ShopRite', holiday: 'pesach', createdAt: '2026-01-20', status: 'draft', tierCount: 4, productCount: 4 },
      { id: 'dh-9', projectName: 'RH 2025 — ShopRite', holiday: 'rosh-hashanah', createdAt: '2025-03-05', status: 'completed', tierCount: 4, productCount: 10 },
      { id: 'dh-10', projectName: 'Sukkos 2025 — ShopRite', holiday: 'sukkos', createdAt: '2025-07-15', status: 'completed', tierCount: 3, productCount: 5 },
      { id: 'dh-11', projectName: 'Pesach 2025 — ShopRite', holiday: 'pesach', createdAt: '2025-01-10', status: 'completed', tierCount: 4, productCount: 8 },
    ],
    notes: 'Strongest kosher aisle penetration in the tri-state area. Co-op owned — each store can make independent display decisions. Key account for Tuscanini line.',
  },
  {
    id: 'ret-4',
    kaycoAccountPatterns: ['STOP & SHOP'],
    name: 'Stop & Shop',
    status: 'active',
    tier: 'standard',
    defaultTierCount: 3,
    maxDisplayHeight: 54,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 400,
    regions: ['Northeast', 'New England'],
    headquartersCity: 'Quincy',
    headquartersState: 'MA',
    accountManager: 'Rachel Hoffman',
    contractStart: '2025-01-01',
    contractEnd: '2026-12-31',
    website: 'stopandshop.com',
    tags: ['growing-account', 'northeast-focus'],
    contacts: [
      { id: 'c-9', name: "Karen O'Brien", title: 'Category Manager — International', email: 'k.obrien@stopandshop.com', phone: '(617) 555-0188', isPrimary: true },
      { id: 'c-10', name: 'James Petrov', title: 'Merchandising Coordinator', email: 'j.petrov@stopandshop.com', phone: '(617) 555-0204', isPrimary: false },
    ],
    authorizedItems: [],
    compliance: [
      { id: 'comp-15', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-01-25', nextAuditDate: '2026-07-25' },
      { id: 'comp-16', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-02-10', nextAuditDate: '2026-08-10' },
      { id: 'comp-17', requirement: 'Kosher Certification Documentation', status: 'action-required', lastAuditDate: '2025-10-15', nextAuditDate: '2026-04-15', notes: 'Renewal documentation pending for 3 Haddar SKUs' },
    ],
    performance: { totalRevenueMTD: 67800, totalRevenueYTD: 412000, avgOrderValue: 5400, fillRate: 91.3, onTimeDelivery: 89.7, returnRate: 2.4, displayComplianceScore: 78 },
    displayHistory: [
      { id: 'dh-12', projectName: 'RH 2026 — Stop & Shop', holiday: 'rosh-hashanah', createdAt: '2026-03-05', status: 'draft', tierCount: 3, productCount: 4 },
      { id: 'dh-13', projectName: 'RH 2025 — Stop & Shop', holiday: 'rosh-hashanah', createdAt: '2025-03-15', status: 'completed', tierCount: 3, productCount: 5 },
    ],
    notes: 'Growing account. Expanding kosher section in NE stores. Lower display height limit (54") — plan tiers accordingly.',
  },
  {
    id: 'ret-5',
    kaycoAccountPatterns: ['KROGER'],
    name: 'Kroger',
    status: 'active',
    tier: 'premium',
    defaultTierCount: 4,
    maxDisplayHeight: 60,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 2750,
    regions: ['Midwest', 'Southeast', 'Southwest', 'West'],
    headquartersCity: 'Cincinnati',
    headquartersState: 'OH',
    accountManager: 'David Greenfield',
    contractStart: '2025-06-01',
    contractEnd: '2027-05-31',
    website: 'kroger.com',
    tags: ['new-2025', 'high-potential', 'multi-banner'],
    contacts: [
      { id: 'c-11', name: 'Patricia Holmes', title: 'Director of Specialty Procurement', email: 'p.holmes@kroger.com', phone: '(513) 555-0312', isPrimary: true },
      { id: 'c-12', name: 'Robert Yang', title: 'Display Program Manager', email: 'r.yang@kroger.com', phone: '(513) 555-0345', isPrimary: false },
    ],
    authorizedItems: [],
    compliance: [
      { id: 'comp-18', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-02-28', nextAuditDate: '2026-08-28' },
      { id: 'comp-19', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-01-20', nextAuditDate: '2026-07-20' },
      { id: 'comp-20', requirement: 'Kosher Certification Documentation', status: 'pending-review', lastAuditDate: '2025-12-15', nextAuditDate: '2026-06-15', notes: 'Initial certification review in progress' },
    ],
    performance: { totalRevenueMTD: 112400, totalRevenueYTD: 645000, avgOrderValue: 9800, fillRate: 94.6, onTimeDelivery: 92.3, returnRate: 1.5, displayComplianceScore: 85 },
    displayHistory: [
      { id: 'dh-14', projectName: 'RH 2026 — Kroger', holiday: 'rosh-hashanah', createdAt: '2026-03-10', status: 'draft', tierCount: 4, productCount: 4 },
    ],
    notes: 'New account as of mid-2025. Multi-banner retailer (Kroger, Ralphs, Fred Meyer, Harris Teeter). Huge upside potential.',
  },
  {
    id: 'ret-6',
    name: 'Whole Foods',
    status: 'active',
    tier: 'premium',
    defaultTierCount: 3,
    maxDisplayHeight: 56,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 530,
    regions: ['Northeast', 'West', 'Southeast', 'Southwest'],
    headquartersCity: 'Austin',
    headquartersState: 'TX',
    accountManager: 'Rachel Hoffman',
    contractStart: '2026-04-01',
    contractEnd: '2028-03-31',
    website: 'wholefoodsmarket.com',
    tags: ['premium-positioning', 'organic-focus', 'onboarding'],
    contacts: [
      { id: 'c-13', name: 'Emily Chen', title: 'Global Buyer — Specialty Grocery', email: 'e.chen@wholefoods.com', phone: '(512) 555-0401', isPrimary: true },
    ],
    authorizedItems: [],
    compliance: [
      { id: 'comp-21', requirement: 'Pallet Display Height Standards', status: 'pending-review', lastAuditDate: '2026-03-20', nextAuditDate: '2026-09-20', notes: 'Initial compliance review scheduled' },
      { id: 'comp-22', requirement: 'Organic/Non-GMO Verification', status: 'pending-review', lastAuditDate: '2026-03-25', nextAuditDate: '2026-06-25', notes: 'Required for Whole Foods — documentation submitted' },
    ],
    performance: { totalRevenueMTD: 0, totalRevenueYTD: 0, avgOrderValue: 0, fillRate: 0, onTimeDelivery: 0, returnRate: 0, displayComplianceScore: 0 },
    displayHistory: [],
    notes: 'Onboarding in progress. Premium positioning — Tuscanini line is the lead. Strict quality and labeling standards.',
  },
  {
    id: 'ret-7',
    name: 'ALDI',
    status: 'inactive',
    tier: 'standard',
    defaultTierCount: 3,
    maxDisplayHeight: 54,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 2300,
    regions: ['Midwest', 'Southeast', 'Northeast'],
    headquartersCity: 'Batavia',
    headquartersState: 'IL',
    accountManager: 'David Greenfield',
    contractStart: '2023-01-01',
    contractEnd: '2025-12-31',
    website: 'aldi.us',
    tags: ['contract-expired', 'review-q2'],
    contacts: [
      { id: 'c-14', name: 'Thomas Weber', title: 'Buying Director', email: 't.weber@aldi.us', phone: '(630) 555-0178', isPrimary: true },
    ],
    authorizedItems: [],
    compliance: [
      { id: 'comp-23', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2025-08-15', nextAuditDate: '2026-02-15' },
    ],
    performance: { totalRevenueMTD: 0, totalRevenueYTD: 0, avgOrderValue: 0, fillRate: 0, onTimeDelivery: 0, returnRate: 0, displayComplianceScore: 0 },
    displayHistory: [
      { id: 'dh-15', projectName: 'RH 2025 — ALDI', holiday: 'rosh-hashanah', createdAt: '2025-02-20', status: 'completed', tierCount: 3, productCount: 2 },
    ],
    notes: 'Contract expired Dec 2025. Low margins made the relationship difficult. Under review for potential renewal with better terms in Q2 2026.',
  },
]


// Demo team so the salesman workspace works out of the box in a fresh
// browser. Managers can rename, reassign, or delete them on /assignments;
// any change persists to localStorage and this seed never reappears.
export const mockSalespeople: Salesperson[] = [
  {
    id: 'sp-1',
    name: 'Sam Klein',
    retailerIds: ['ret-1', 'ret-2', 'ret-7'],
    createdAt: 1767225600000, // Jan 1 2026
  },
  {
    id: 'sp-2',
    name: 'Dani Gold',
    retailerIds: ['ret-3', 'ret-4', 'ret-5', 'ret-6'],
    createdAt: 1767225600000,
  },
]
