import type { Product } from '../types'

export function withProductPlanningDefaults(product: Product): Product {
  const caseWidth = product.caseWidth ?? product.width
  const caseDepth = product.caseDepth ?? product.depth
  const caseHeight = product.caseHeight ?? product.height
  const caseWeight = product.caseWeight ?? product.weight

  const defaultShelfReadyTray =
    product.caseConfig?.caseStyle === 'tray' ||
    product.caseConfig?.caseStyle === 'open-top'

  return {
    ...product,
    allowedOrientations: product.allowedOrientations ?? ['upright'],
    stackable: product.stackable ?? true,
    fragile: product.fragile ?? false,
    crushable: product.crushable ?? false,
    maxStackLoadLb: product.maxStackLoadLb ?? Math.max(0, caseWeight * 10),
    nestingPercent: product.nestingPercent ?? 0,
    caseWidth,
    caseDepth,
    caseHeight,
    caseWeight,
    shelfReadyTray: product.shelfReadyTray ?? defaultShelfReadyTray,
    heroImageUrl: product.heroImageUrl ?? product.imageUrl,
  }
}

function normalizeSourceProduct(product: Product): Product {
  const normalized = withProductPlanningDefaults(product)

  if (normalized.caseConfig) {
    return {
      ...normalized,
      variantType: 'case',
      parentProductId: normalized.parentProductId ?? normalized.caseConfig.unitProductId,
      autoGeneratedCase: normalized.autoGeneratedCase ?? false,
    }
  }

  return {
    ...normalized,
    variantType: 'single',
    parentProductId: normalized.parentProductId ?? normalized.id,
    autoGeneratedCase: false,
  }
}

export function normalizeProductsWithVariants(products: Product[]) {
  const sourceProducts = products.filter((product) => !product.autoGeneratedCase)
  const normalizedSources = sourceProducts.map(normalizeSourceProduct)

  const ordered: Product[] = []
  normalizedSources.forEach((product) => {
    ordered.push(product)

    const relatedManualCases = normalizedSources.filter(
      (candidate) =>
        candidate.caseConfig &&
        candidate.id !== product.id &&
        candidate.parentProductId === product.id,
    )

    relatedManualCases.forEach((candidate) => {
      if (!ordered.some((entry) => entry.id === candidate.id)) {
        ordered.push(candidate)
      }
    })

  })

  const seen = new Set<string>()
  return ordered.filter((product) => {
    if (seen.has(product.id)) return false
    seen.add(product.id)
    return true
  })
}
