import type { Orientation3D, Product } from '../../types'
import { calculateCaseDimensions } from '../dimensionEngine'
import { withProductPlanningDefaults } from '../product-variants'

export interface EffectiveCaseDimensions {
  width: number
  depth: number
  height: number
}

function hasExplicitCaseDimensions(product: Product): boolean {
  return (
    typeof product.caseWidth === 'number' ||
    typeof product.caseDepth === 'number' ||
    typeof product.caseHeight === 'number'
  )
}

function estimateLayout(unitsPerCase: number) {
  const layers = unitsPerCase >= 18 ? 2 : 1
  const perLayer = Math.ceil(unitsPerCase / layers)
  const cols = Math.max(1, Math.ceil(Math.sqrt(perLayer)))
  const rows = Math.max(1, Math.ceil(perLayer / cols))
  return { cols, rows, layers }
}

function getBaseCaseDimensions(product: Product): EffectiveCaseDimensions {
  if (hasExplicitCaseDimensions(product)) {
    return {
      width: product.caseWidth ?? product.width,
      depth: product.caseDepth ?? product.depth,
      height: product.caseHeight ?? product.height,
    }
  }

  if (product.caseConfig || product.variantType === 'case' || product.autoGeneratedCase) {
    return {
      width: product.width,
      depth: product.depth,
      height: product.height,
    }
  }

  const unitsPerCase = Math.max(1, Math.floor(product.unitsPerCase ?? 1))
  if (unitsPerCase <= 1) {
    return {
      width: product.width,
      depth: product.depth,
      height: product.height,
    }
  }

  const footprint = product.width * product.depth
  const likelyUnitDimensions = footprint <= 64 || Math.min(product.width, product.depth) <= 4.5
  if (!likelyUnitDimensions) {
    return {
      width: product.width,
      depth: product.depth,
      height: product.height,
    }
  }

  const estimated = calculateCaseDimensions(
    {
      width: product.width,
      depth: product.depth,
      height: product.height,
      source: 'manual',
    },
    estimateLayout(unitsPerCase),
    0.25,
    false,
  )

  return {
    width: estimated.width,
    depth: estimated.depth,
    height: estimated.height,
  }
}

function applyOrientation(
  dimensions: EffectiveCaseDimensions,
  orientation: Orientation3D,
): EffectiveCaseDimensions {
  switch (orientation) {
    case 'upright':
    case 'inverted':
      return dimensions
    case 'on-side':
      return {
        width: dimensions.width,
        depth: dimensions.height,
        height: dimensions.depth,
      }
    case 'on-end':
      return {
        width: dimensions.height,
        depth: dimensions.depth,
        height: dimensions.width,
      }
  }
}

function applyRotation(
  dimensions: EffectiveCaseDimensions,
  rotationDeg: 0 | 90 | 180 | 270,
): EffectiveCaseDimensions {
  if (rotationDeg === 90 || rotationDeg === 270) {
    return {
      width: dimensions.depth,
      depth: dimensions.width,
      height: dimensions.height,
    }
  }

  return dimensions
}

export function getEffectiveCaseDimensions(
  product: Product,
  orientation: Orientation3D = 'upright',
  rotationDeg: 0 | 90 | 180 | 270 = 0,
): EffectiveCaseDimensions {
  const base = getBaseCaseDimensions(product)

  return applyRotation(applyOrientation(base, orientation), rotationDeg)
}

export function isOrientationAllowed(
  product: Product,
  orientation: Orientation3D = 'upright',
): boolean {
  return (withProductPlanningDefaults(product).allowedOrientations ?? ['upright']).includes(
    orientation,
  )
}
