import type { Product } from "@/types/product";

export interface Customer {
  id: string;
  name: string;
  products: Product[];
}

export const CUSTOMERS: Customer[] = [
  {
    id: "kroger",
    name: "Kroger",
    products: [
      {
        id: "kr-001",
        sku: "KR-CHR-001",
        name: "Chocolate Coins",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 8, height: 10, depth: 6 },
        color: "#c59c45",
        unitPrice: 7.99,
        unitsPerCase: 12,
      },
      {
        id: "kr-002",
        sku: "KR-CHR-014",
        name: "Marshmallow Twists",
        category: "Snacks",
        holiday: "christmas",
        dimensions: { width: 6, height: 9, depth: 4 },
        color: "#cf5d55",
        unitPrice: 5.49,
        unitsPerCase: 18,
      },
      {
        id: "kr-003",
        sku: "KR-HAN-022",
        name: "Mini Menorah Kit",
        category: "Traditions",
        holiday: "hanukkah",
        dimensions: { width: 9, height: 8, depth: 3 },
        color: "#2f5f96",
        unitPrice: 11.99,
        unitsPerCase: 8,
      },
      {
        id: "kr-004",
        sku: "KR-PAS-031",
        name: "Matzo Variety Pack",
        category: "Pantry",
        holiday: "passover",
        dimensions: { width: 10, height: 12, depth: 5 },
        color: "#7a9f6d",
        unitPrice: 8.99,
        unitsPerCase: 10,
      },
      {
        id: "kr-005",
        sku: "KR-EVE-008",
        name: "Fruit Slice Gummies",
        category: "Candy",
        holiday: "everyday",
        dimensions: { width: 7, height: 9, depth: 4 },
        color: "#d9733f",
        unitPrice: 4.99,
        unitsPerCase: 20,
      },
      {
        id: "kr-006",
        sku: "KR-ROS-017",
        name: "Honey Sampler",
        category: "Gifts",
        holiday: "rosh-hashanah",
        dimensions: { width: 8, height: 7, depth: 5 },
        color: "#b7832d",
        unitPrice: 14.99,
        unitsPerCase: 6,
      },
      {
        id: "kr-007",
        sku: "KR-CHR-045",
        name: "Dreidel Cookie Box",
        category: "Bakery",
        holiday: "hanukkah",
        dimensions: { width: 7, height: 8, depth: 5 },
        color: "#4a7fb5",
        unitPrice: 6.49,
        unitsPerCase: 14,
      },
      {
        id: "kr-008",
        sku: "KR-EVE-019",
        name: "Trail Mix Pouch",
        category: "Snacks",
        holiday: "everyday",
        dimensions: { width: 6, height: 10, depth: 3 },
        color: "#8b6e4e",
        unitPrice: 5.99,
        unitsPerCase: 16,
      },
      {
        id: "kr-009",
        sku: "KR-CHR-052",
        name: "Peppermint Bark Tin",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 8, height: 6, depth: 8 },
        color: "#c4484a",
        unitPrice: 9.99,
        unitsPerCase: 10,
      },
      {
        id: "kr-010",
        sku: "KR-PAS-040",
        name: "Macaroon Assortment",
        category: "Bakery",
        holiday: "passover",
        dimensions: { width: 9, height: 7, depth: 6 },
        color: "#a67c52",
        unitPrice: 12.99,
        unitsPerCase: 8,
      },
    ],
  },
  {
    id: "meijer",
    name: "Meijer",
    products: [
      {
        id: "mj-001",
        sku: "MJ-CHR-101",
        name: "Holiday Cocoa Set",
        category: "Beverages",
        holiday: "christmas",
        dimensions: { width: 9, height: 11, depth: 5 },
        color: "#6b3a2a",
        unitPrice: 10.99,
        unitsPerCase: 8,
      },
      {
        id: "mj-002",
        sku: "MJ-CHR-102",
        name: "Candy Cane Bundle",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 7, height: 12, depth: 3 },
        color: "#d14545",
        unitPrice: 4.99,
        unitsPerCase: 24,
      },
      {
        id: "mj-003",
        sku: "MJ-HAN-201",
        name: "Gelt Bag",
        category: "Candy",
        holiday: "hanukkah",
        dimensions: { width: 6, height: 8, depth: 4 },
        color: "#d4a843",
        unitPrice: 3.99,
        unitsPerCase: 20,
      },
      {
        id: "mj-004",
        sku: "MJ-EVE-301",
        name: "Sesame Snaps",
        category: "Snacks",
        holiday: "everyday",
        dimensions: { width: 5, height: 7, depth: 3 },
        color: "#c9a96e",
        unitPrice: 3.49,
        unitsPerCase: 30,
      },
      {
        id: "mj-005",
        sku: "MJ-PAS-401",
        name: "Gefilte Fish Jar",
        category: "Pantry",
        holiday: "passover",
        dimensions: { width: 5, height: 9, depth: 5 },
        color: "#7a9a7d",
        unitPrice: 6.99,
        unitsPerCase: 12,
      },
      {
        id: "mj-006",
        sku: "MJ-ROS-501",
        name: "Apple Cake Mix",
        category: "Bakery",
        holiday: "rosh-hashanah",
        dimensions: { width: 7, height: 10, depth: 4 },
        color: "#a84632",
        unitPrice: 5.99,
        unitsPerCase: 14,
      },
      {
        id: "mj-007",
        sku: "MJ-CHR-103",
        name: "Stocking Stuffer Mix",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 8, height: 10, depth: 5 },
        color: "#3d8b37",
        unitPrice: 7.49,
        unitsPerCase: 12,
      },
      {
        id: "mj-008",
        sku: "MJ-HAN-202",
        name: "Sufganiyot Kit",
        category: "Bakery",
        holiday: "hanukkah",
        dimensions: { width: 8, height: 6, depth: 6 },
        color: "#d4813a",
        unitPrice: 8.99,
        unitsPerCase: 10,
      },
      {
        id: "mj-009",
        sku: "MJ-EVE-302",
        name: "Halva Bar",
        category: "Snacks",
        holiday: "everyday",
        dimensions: { width: 4, height: 8, depth: 3 },
        color: "#c5b896",
        unitPrice: 2.99,
        unitsPerCase: 24,
      },
    ],
  },
  {
    id: "harris-teeter",
    name: "Harris Teeter",
    products: [
      {
        id: "ht-001",
        sku: "HT-CHR-501",
        name: "Holiday Gift Tower",
        category: "Gifts",
        holiday: "christmas",
        dimensions: { width: 10, height: 14, depth: 6 },
        color: "#8c2f2f",
        unitPrice: 24.99,
        unitsPerCase: 4,
      },
      {
        id: "ht-002",
        sku: "HT-CHR-502",
        name: "Gingerbread House Kit",
        category: "Bakery",
        holiday: "christmas",
        dimensions: { width: 10, height: 10, depth: 8 },
        color: "#a06030",
        unitPrice: 12.99,
        unitsPerCase: 6,
      },
      {
        id: "ht-003",
        sku: "HT-HAN-601",
        name: "Hanukkah Candle Set",
        category: "Traditions",
        holiday: "hanukkah",
        dimensions: { width: 8, height: 6, depth: 3 },
        color: "#3355aa",
        unitPrice: 8.99,
        unitsPerCase: 12,
      },
      {
        id: "ht-004",
        sku: "HT-PAS-701",
        name: "Seder Plate Set",
        category: "Traditions",
        holiday: "passover",
        dimensions: { width: 12, height: 4, depth: 12 },
        color: "#5c7a3d",
        unitPrice: 18.99,
        unitsPerCase: 4,
      },
      {
        id: "ht-005",
        sku: "HT-EVE-801",
        name: "Dark Chocolate Bark",
        category: "Candy",
        holiday: "everyday",
        dimensions: { width: 7, height: 9, depth: 3 },
        color: "#3d2b1f",
        unitPrice: 6.99,
        unitsPerCase: 16,
      },
      {
        id: "ht-006",
        sku: "HT-ROS-901",
        name: "Pomegranate Juice",
        category: "Beverages",
        holiday: "rosh-hashanah",
        dimensions: { width: 5, height: 11, depth: 5 },
        color: "#8c1c3d",
        unitPrice: 7.49,
        unitsPerCase: 12,
      },
      {
        id: "ht-007",
        sku: "HT-CHR-503",
        name: "Holiday Cookie Tin",
        category: "Bakery",
        holiday: "christmas",
        dimensions: { width: 9, height: 7, depth: 9 },
        color: "#bf3b3b",
        unitPrice: 14.99,
        unitsPerCase: 6,
      },
      {
        id: "ht-008",
        sku: "HT-HAN-602",
        name: "Chocolate Dreidels",
        category: "Candy",
        holiday: "hanukkah",
        dimensions: { width: 6, height: 8, depth: 4 },
        color: "#4a7fb5",
        unitPrice: 5.99,
        unitsPerCase: 18,
      },
      {
        id: "ht-009",
        sku: "HT-EVE-802",
        name: "Tahini Spread",
        category: "Pantry",
        holiday: "everyday",
        dimensions: { width: 5, height: 7, depth: 5 },
        color: "#c9a96e",
        unitPrice: 5.49,
        unitsPerCase: 14,
      },
      {
        id: "ht-010",
        sku: "HT-PAS-702",
        name: "Matzo Ball Soup Mix",
        category: "Pantry",
        holiday: "passover",
        dimensions: { width: 6, height: 8, depth: 4 },
        color: "#c4a35a",
        unitPrice: 4.49,
        unitsPerCase: 16,
      },
    ],
  },
];

export function getCustomerById(id: string) {
  return CUSTOMERS.find((c) => c.id === id);
}
