import type { Product, PackagingShape } from "@/types/product";

export interface PalletHistory {
  id: string;
  name: string;
  date: string;
  skuCount: number;
  status: "delivered" | "in-transit" | "pending" | "completed";
}

export interface Customer {
  id: string;
  name: string;
  contact: string;
  email: string;
  phone: string;
  address: string;
  status: "Priority" | "Standard" | "Urgent" | "Inactive";
  products: Product[];
  palletHistory: PalletHistory[];
}

export const CUSTOMERS: Customer[] = [
  {
    id: "kroger",
    name: "Kroger",
    contact: "Sarah Jenkins",
    email: "s.jenkins@kroger.com",
    phone: "(513) 762-4000",
    address: "1014 Vine St, Cincinnati, OH 45202",
    status: "Priority",
    products: [
      {
        id: "kr-001",
        sku: "KR-CHR-001",
        name: "Chocolate Coins",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 8, height: 10, depth: 6 },
        color: "#c59c45",
        packaging: "tin",
        unitPrice: 7.99,
        unitsPerCase: 12,
      },
      {
        id: "kr-002",
        sku: "KR-CHR-014",
        name: "Marshmallow Twists",
        category: "Snacks",
        holiday: "christmas",
        dimensions: { width: 6, height: 9, depth: 4 },
        color: "#cf5d55",
        packaging: "bag",
        unitPrice: 5.49,
        unitsPerCase: 18,
      },
      {
        id: "kr-003",
        sku: "KR-HAN-022",
        name: "Mini Menorah Kit",
        category: "Traditions",
        holiday: "hanukkah",
        dimensions: { width: 9, height: 8, depth: 3 },
        color: "#2f5f96",
        packaging: "box",
        unitPrice: 11.99,
        unitsPerCase: 8,
      },
      {
        id: "kr-004",
        sku: "KR-PAS-031",
        name: "Matzo Variety Pack",
        category: "Pantry",
        holiday: "passover",
        dimensions: { width: 10, height: 12, depth: 5 },
        color: "#7a9f6d",
        packaging: "box",
        unitPrice: 8.99,
        unitsPerCase: 10,
      },
      {
        id: "kr-005",
        sku: "KR-EVE-008",
        name: "Fruit Slice Gummies",
        category: "Candy",
        holiday: "everyday",
        dimensions: { width: 7, height: 9, depth: 4 },
        color: "#d9733f",
        packaging: "pouch",
        unitPrice: 4.99,
        unitsPerCase: 20,
      },
      {
        id: "kr-006",
        sku: "KR-ROS-017",
        name: "Honey Sampler",
        category: "Gifts",
        holiday: "rosh-hashanah",
        dimensions: { width: 8, height: 7, depth: 5 },
        color: "#b7832d",
        packaging: "jar",
        unitPrice: 14.99,
        unitsPerCase: 6,
      },
      {
        id: "kr-007",
        sku: "KR-CHR-045",
        name: "Dreidel Cookie Box",
        category: "Bakery",
        holiday: "hanukkah",
        dimensions: { width: 7, height: 8, depth: 5 },
        color: "#4a7fb5",
        packaging: "box",
        unitPrice: 6.49,
        unitsPerCase: 14,
      },
      {
        id: "kr-008",
        sku: "KR-EVE-019",
        name: "Trail Mix Pouch",
        category: "Snacks",
        holiday: "everyday",
        dimensions: { width: 6, height: 10, depth: 3 },
        color: "#8b6e4e",
        packaging: "pouch",
        unitPrice: 5.99,
        unitsPerCase: 16,
      },
      {
        id: "kr-009",
        sku: "KR-CHR-052",
        name: "Peppermint Bark Tin",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 8, height: 6, depth: 8 },
        color: "#c4484a",
        packaging: "tin",
        unitPrice: 9.99,
        unitsPerCase: 10,
      },
      {
        id: "kr-010",
        sku: "KR-PAS-040",
        name: "Macaroon Assortment",
        category: "Bakery",
        holiday: "passover",
        dimensions: { width: 9, height: 7, depth: 6 },
        color: "#a67c52",
        packaging: "box",
        unitPrice: 12.99,
        unitsPerCase: 8,
      },
    ],
    palletHistory: [
      { id: "p-kr-1", name: "Mixed Produce #482", date: "2026-03-16", skuCount: 8, status: "delivered" },
      { id: "p-kr-2", name: "Holiday Candy #310", date: "2026-03-12", skuCount: 6, status: "delivered" },
      { id: "p-kr-3", name: "Passover Bundle #88", date: "2026-03-08", skuCount: 4, status: "completed" },
      { id: "p-kr-4", name: "Everyday Snacks #201", date: "2026-02-28", skuCount: 10, status: "completed" },
    ],
  },
  {
    id: "meijer",
    name: "Meijer",
    contact: "David Vane",
    email: "d.vane@meijer.com",
    phone: "(616) 453-6711",
    address: "2929 Walker Ave NW, Grand Rapids, MI 49544",
    status: "Standard",
    products: [
      {
        id: "mj-001",
        sku: "MJ-CHR-101",
        name: "Holiday Cocoa Set",
        category: "Beverages",
        holiday: "christmas",
        dimensions: { width: 9, height: 11, depth: 5 },
        color: "#6b3a2a",
        packaging: "box",
        unitPrice: 10.99,
        unitsPerCase: 8,
      },
      {
        id: "mj-002",
        sku: "MJ-CHR-102",
        name: "Candy Cane Bundle",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 7, height: 12, depth: 3 },
        color: "#d14545",
        packaging: "bag",
        unitPrice: 4.99,
        unitsPerCase: 24,
      },
      {
        id: "mj-003",
        sku: "MJ-HAN-201",
        name: "Gelt Bag",
        category: "Candy",
        holiday: "hanukkah",
        dimensions: { width: 6, height: 8, depth: 4 },
        color: "#d4a843",
        packaging: "bag",
        unitPrice: 3.99,
        unitsPerCase: 20,
      },
      {
        id: "mj-004",
        sku: "MJ-EVE-301",
        name: "Sesame Snaps",
        category: "Snacks",
        holiday: "everyday",
        dimensions: { width: 5, height: 7, depth: 3 },
        color: "#c9a96e",
        packaging: "pouch",
        unitPrice: 3.49,
        unitsPerCase: 30,
      },
      {
        id: "mj-005",
        sku: "MJ-PAS-401",
        name: "Gefilte Fish Jar",
        category: "Pantry",
        holiday: "passover",
        dimensions: { width: 5, height: 9, depth: 5 },
        color: "#7a9a7d",
        packaging: "jar",
        unitPrice: 6.99,
        unitsPerCase: 12,
      },
      {
        id: "mj-006",
        sku: "MJ-ROS-501",
        name: "Apple Cake Mix",
        category: "Bakery",
        holiday: "rosh-hashanah",
        dimensions: { width: 7, height: 10, depth: 4 },
        color: "#a84632",
        packaging: "box",
        unitPrice: 5.99,
        unitsPerCase: 14,
      },
      {
        id: "mj-007",
        sku: "MJ-CHR-103",
        name: "Stocking Stuffer Mix",
        category: "Candy",
        holiday: "christmas",
        dimensions: { width: 8, height: 10, depth: 5 },
        color: "#3d8b37",
        packaging: "bag",
        unitPrice: 7.49,
        unitsPerCase: 12,
      },
      {
        id: "mj-008",
        sku: "MJ-HAN-202",
        name: "Sufganiyot Kit",
        category: "Bakery",
        holiday: "hanukkah",
        dimensions: { width: 8, height: 6, depth: 6 },
        color: "#d4813a",
        packaging: "box",
        unitPrice: 8.99,
        unitsPerCase: 10,
      },
      {
        id: "mj-009",
        sku: "MJ-EVE-302",
        name: "Halva Bar",
        category: "Snacks",
        holiday: "everyday",
        dimensions: { width: 4, height: 8, depth: 3 },
        color: "#c5b896",
        packaging: "pouch",
        unitPrice: 2.99,
        unitsPerCase: 24,
      },
    ],
    palletHistory: [
      { id: "p-mj-1", name: "Dry Goods #991", date: "2026-03-14", skuCount: 5, status: "in-transit" },
      { id: "p-mj-2", name: "Hanukkah Specials #44", date: "2026-03-01", skuCount: 3, status: "completed" },
    ],
  },
  {
    id: "harris-teeter",
    name: "Harris Teeter",
    contact: "Michael Ross",
    email: "mross@ht.com",
    phone: "(704) 844-3100",
    address: "701 Crestdale Rd, Matthews, NC 28105",
    status: "Urgent",
    products: [
      {
        id: "ht-001",
        sku: "HT-CHR-501",
        name: "Holiday Gift Tower",
        category: "Gifts",
        holiday: "christmas",
        dimensions: { width: 10, height: 14, depth: 6 },
        color: "#8c2f2f",
        packaging: "box",
        unitPrice: 24.99,
        unitsPerCase: 4,
      },
      {
        id: "ht-002",
        sku: "HT-CHR-502",
        name: "Gingerbread House Kit",
        category: "Bakery",
        holiday: "christmas",
        dimensions: { width: 10, height: 10, depth: 8 },
        color: "#a06030",
        packaging: "box",
        unitPrice: 12.99,
        unitsPerCase: 6,
      },
      {
        id: "ht-003",
        sku: "HT-HAN-601",
        name: "Hanukkah Candle Set",
        category: "Traditions",
        holiday: "hanukkah",
        dimensions: { width: 8, height: 6, depth: 3 },
        color: "#3355aa",
        packaging: "box",
        unitPrice: 8.99,
        unitsPerCase: 12,
      },
      {
        id: "ht-004",
        sku: "HT-PAS-701",
        name: "Seder Plate Set",
        category: "Traditions",
        holiday: "passover",
        dimensions: { width: 12, height: 4, depth: 12 },
        color: "#5c7a3d",
        packaging: "box",
        unitPrice: 18.99,
        unitsPerCase: 4,
      },
      {
        id: "ht-005",
        sku: "HT-EVE-801",
        name: "Dark Chocolate Bark",
        category: "Candy",
        holiday: "everyday",
        dimensions: { width: 7, height: 9, depth: 3 },
        color: "#3d2b1f",
        packaging: "bag",
        unitPrice: 6.99,
        unitsPerCase: 16,
      },
      {
        id: "ht-006",
        sku: "HT-ROS-901",
        name: "Pomegranate Juice",
        category: "Beverages",
        holiday: "rosh-hashanah",
        dimensions: { width: 5, height: 11, depth: 5 },
        color: "#8c1c3d",
        packaging: "bottle",
        unitPrice: 7.49,
        unitsPerCase: 12,
      },
      {
        id: "ht-007",
        sku: "HT-CHR-503",
        name: "Holiday Cookie Tin",
        category: "Bakery",
        holiday: "christmas",
        dimensions: { width: 9, height: 7, depth: 9 },
        color: "#bf3b3b",
        packaging: "tin",
        unitPrice: 14.99,
        unitsPerCase: 6,
      },
      {
        id: "ht-008",
        sku: "HT-HAN-602",
        name: "Chocolate Dreidels",
        category: "Candy",
        holiday: "hanukkah",
        dimensions: { width: 6, height: 8, depth: 4 },
        color: "#4a7fb5",
        packaging: "bag",
        unitPrice: 5.99,
        unitsPerCase: 18,
      },
      {
        id: "ht-009",
        sku: "HT-EVE-802",
        name: "Tahini Spread",
        category: "Pantry",
        holiday: "everyday",
        dimensions: { width: 5, height: 7, depth: 5 },
        color: "#c9a96e",
        packaging: "jar",
        unitPrice: 5.49,
        unitsPerCase: 14,
      },
      {
        id: "ht-010",
        sku: "HT-PAS-702",
        name: "Matzo Ball Soup Mix",
        category: "Pantry",
        holiday: "passover",
        dimensions: { width: 6, height: 8, depth: 4 },
        color: "#c4a35a",
        packaging: "box",
        unitPrice: 4.49,
        unitsPerCase: 16,
      },
    ],
    palletHistory: [
      { id: "p-ht-1", name: "Frozen Tier #112", date: "2026-03-15", skuCount: 7, status: "pending" },
      { id: "p-ht-2", name: "Gift Tower Display #55", date: "2026-03-10", skuCount: 4, status: "delivered" },
      { id: "p-ht-3", name: "Christmas Bakery #78", date: "2026-02-20", skuCount: 6, status: "completed" },
    ],
  },
  {
    id: "publix",
    name: "Publix Markets",
    contact: "Linda Chao",
    email: "lchao@publix.com",
    phone: "(863) 688-1188",
    address: "3300 Publix Corporate Pkwy, Lakeland, FL 33811",
    status: "Inactive",
    products: [
      {
        id: "pb-001",
        sku: "PB-CHR-101",
        name: "Holiday Fudge Box",
        category: "Candy",
        holiday: "christmas" as const,
        dimensions: { width: 8, height: 6, depth: 5 },
        color: "#7c3a2d",
        packaging: "box",
        unitPrice: 9.99,
        unitsPerCase: 10,
      },
      {
        id: "pb-002",
        sku: "PB-EVE-201",
        name: "Mixed Nut Tin",
        category: "Snacks",
        holiday: "everyday" as const,
        dimensions: { width: 7, height: 8, depth: 7 },
        color: "#a68b5b",
        packaging: "tin",
        unitPrice: 11.99,
        unitsPerCase: 8,
      },
      {
        id: "pb-003",
        sku: "PB-PAS-301",
        name: "Charoset Jar",
        category: "Pantry",
        holiday: "passover" as const,
        dimensions: { width: 5, height: 7, depth: 5 },
        color: "#8b5e3c",
        packaging: "jar",
        unitPrice: 6.49,
        unitsPerCase: 14,
      },
    ],
    palletHistory: [
      { id: "p-pb-1", name: "Bakery Mix #301", date: "2026-03-12", skuCount: 3, status: "completed" },
    ],
  },
];

export function getCustomerById(id: string) {
  return CUSTOMERS.find((c) => c.id === id);
}
